### ISSUE TITLE
Create Spring data jpa service for Owners

### ISSUE THREAD

**Issue by antoinedga** [antoinedga/sfg-pet-clinic#31]

**Comment by Shiroo77** [comment]
Hello, I would like to work on this. Can you elaborate more details about the issue ?

**Comment by antoinedga** [comment]
this is a project within a udemy course, this isnt for anyone else to colab with. @Shiroo77

**Comment by Shiroo77** [comment]
Would you mind sharing the udemy course ? You haven't mentioned it in the README file.

**Comment by antoinedga** [comment]
Spring Framework 5: Learn Spring Framework 5, Spring Boot 2, Spring MVC, Spring Data JPA, Spring Data MongoDB, Hibernate
@Shiroo77

**Comment by antoinedga** [comment]
in the read me it literally says practicing spring framework udemy course
